### ISSUE TITLE
Add Json Web Token Support

### ISSUE THREAD

**Issue by SvenTo** [takeshixx/deen#19]
Please add support for Json Web Token:
https://pyjwt.readthedocs.io/en/latest/

**Comment by pcrossy** [comment]
maybe add "pip3 install pyjwt" to the installation guide, otherwise dependency is missing.

**Comment by takeshixx** [comment]
pyjwt is part of the `requirements.txt` and should be installed like this:

```
pip install -r requirements.txt
```

Added an installation hint in 8b5285f32d92727016c9f0ac621ddbd631662939, currently only in the develop branch. Will be moved to master with next minor release.

**Comment by takeshixx** [comment]
Updated dependencies in a6e5122c4c5266511d051dffb9afaf729309c5b8 and added an extra hint for optional dependencies that might have to be installed via package managers. Also splitted requirements for Python 2 and 3 because PyQt is only installable via pip on Python >3.5.

**Comment by takeshixx** [comment]
v2.0.0b1 implements JWT, but there are limitations due to bugs in the used JWT module:
* Shared secrets that just contain numbers do not work.
* Shared keys that include public keys do not work.
I've forked the repository and fixed these two issues. But there might be more bugs. If these features are required, the fork should be used until the bugs are fixed in upstream.
